[workspace]
members = [
	"lib/rust",
	"scaffold",
	"scaffold/aoc-query",
	"2015/01/rust",
	"2015/02/rust",
	"2015/03/rust",
	"2015/04/rust",
	"2015/05/rust",
	"2016/01/rust",
	"2018/01/rust",
]

[profile.bench]
lto = true

[profile.release]
overflow-checks = true

[profile.dev]
opt-level = 3
